export const TURKEY_CITIES = [
  { name: "Adana", districts: ["Seyhan", "Çukurova", "Sarıçam", "Yüreğir", "Ceyhan", "Kozan"] },
  { name: "Adıyaman", districts: ["Merkez", "Kahta", "Besni", "Gölbaşı", "Gerger"] },
  { name: "Afyonkarahisar", districts: ["Merkez", "Sandıklı", "Dinar", "Bolvadin", "Emirdağ"] },
  { name: "Ağrı", districts: ["Merkez", "Patnos", "Doğubayazıt", "Diyadin", "Eleşkirt"] },
  { name: "Amasya", districts: ["Merkez", "Merzifon", "Suluova", "Taşova", "Gümüşhacıköy"] },
  { name: "Ankara", districts: ["Çankaya", "Keçiören", "Yenimahalle", "Mamak", "Etimesgut", "Sincan", "Altındağ", "Pursaklar", "Gölbaşı"] },
  { name: "Antalya", districts: ["Muratpaşa", "Kepez", "Konyaaltı", "Alanya", "Manavgat", "Serik", "Aksu", "Döşemealtı", "Kumluca"] },
  { name: "Artvin", districts: ["Merkez", "Hopa", "Arhavi", "Borçka", "Ardanuç"] },
  { name: "Aydın", districts: ["Efeler", "Nazilli", "Söke", "Kuşadası", "Didim", "Çine", "İncirliova"] },
  { name: "Balıkesir", districts: ["Karesi", "Altıeylül", "Bandırma", "Edremit", "Gönen", "Ayvalık", "Burhaniye"] },
  { name: "Bilecik", districts: ["Merkez", "Bozüyük", "Osmaneli", "Söğüt", "Pazaryeri"] },
  { name: "Bingöl", districts: ["Merkez", "Genç", "Solhan", "Karlıova", "Adaklı"] },
  { name: "Bitlis", districts: ["Merkez", "Tatvan", "Güroymak", "Ahlat", "Hizan"] },
  { name: "Bolu", districts: ["Merkez", "Gerede", "Mudurnu", "Göynük", "Mengen"] },
  { name: "Burdur", districts: ["Merkez", "Bucak", "Gölhisar", "Yeşilova", "Tefenni"] },
  { name: "Bursa", districts: ["Osmangazi", "Nilüfer", "Yıldırım", "İnegöl", "Gemlik", "Mudanya", "Gürsu", "Kestel", "Mustafakemalpaşa"] },
  { name: "Çanakkale", districts: ["Merkez", "Biga", "Çan", "Gelibolu", "Ayvacık", "Ezine"] },
  { name: "Çankırı", districts: ["Merkez", "Çerkeş", "Ilgaz", "Orta", "Şabanözü"] },
  { name: "Çorum", districts: ["Merkez", "Sungurlu", "Osmancık", "İskilip", "Alaca"] },
  { name: "Denizli", districts: ["Pamukkale", "Merkezefendi", "Acıpayam", "Tavas", "Honaz", "Sarayköy"] },
  { name: "Diyarbakır", districts: ["Bağlar", "Kayapınar", "Yenişehir", "Sur", "Ergani", "Bismil", "Silvan"] },
  { name: "Edirne", districts: ["Merkez", "Keşan", "Uzunköprü", "İpsala", "Havsa"] },
  { name: "Elazığ", districts: ["Merkez", "Kovancılar", "Karakoçan", "Palu", "Arıcak"] },
  { name: "Erzincan", districts: ["Merkez", "Tercan", "Üzümlü", "Çayırlı", "İliç"] },
  { name: "Erzurum", districts: ["Yakutiye", "Palandöken", "Aziziye", "Horasan", "Oltu", "Pasinler"] },
  { name: "Eskişehir", districts: ["Odunpazarı", "Tepebaşı", "Sivrihisar", "Çifteler", "Alpu"] },
  { name: "Gaziantep", districts: ["Şahinbey", "Şehitkamil", "Nizip", "İslahiye", "Nurdağı", "Araban"] },
  { name: "Giresun", districts: ["Merkez", "Bulancak", "Espiye", "Görele", "Tirebolu"] },
  { name: "Gümüşhane", districts: ["Merkez", "Kelkit", "Şiran", "Kürtün", "Torul"] },
  { name: "Hakkari", districts: ["Merkez", "Yüksekova", "Şemdinli", "Çukurca"] },
  { name: "Hatay", districts: ["Antakya", "İskenderun", "Defne", "Dörtyol", "Samandağ", "Kırıkhan", "Reyhanlı"] },
  { name: "Isparta", districts: ["Merkez", "Eğirdir", "Şarkikaraağaç", "Gelendost", "Yalvaç"] },
  { name: "Mersin", districts: ["Tarsus", "Toroslar", "Yenişehir", "Mezitli", "Akdeniz", "Silifke", "Erdemli", "Anamur"] },
  { name: "İstanbul", districts: ["Kadıköy", "Beşiktaş", "Şişli", "Üsküdar", "Maltepe", "Esenyurt", "Küçükçekmece", "Bağcılar", "Pendik", "Ümraniye", "Fatih", "Sarıyer", "Beylikdüzü", "Bakırköy"] },
  { name: "İzmir", districts: ["Konak", "Karşıyaka", "Bornova", "Buca", "Çiğli", "Torbalı", "Menemen", "Gaziemir", "Ödemiş", "Kemalpaşa", "Bergama"] },
  { name: "Kars", districts: ["Merkez", "Kağızman", "Sarıkamış", "Selim", "Digor"] },
  { name: "Kastamonu", districts: ["Merkez", "Tosya", "Taşköprü", "İnebolu", "Cide"] },
  { name: "Kayseri", districts: ["Melikgazi", "Kocasinan", "Talas", "Develi", "Yahyalı", "Bünyan"] },
  { name: "Kırklareli", districts: ["Merkez", "Lüleburgaz", "Babaeski", "Vize", "Pınarhisar"] },
  { name: "Kırşehir", districts: ["Merkez", "Kaman", "Mucur", "Çiçekdağı", "Akpınar"] },
  { name: "Kocaeli", districts: ["Gebze", "İzmit", "Darıca", "Körfez", "Gölcük", "Derince", "Çayırova", "Kartepe", "Başiskele"] },
  { name: "Konya", districts: ["Selçuklu", "Meram", "Karatay", "Ereğli", "Akşehir", "Beyşehir", "Seydişehir", "Cihanbeyli"] },
  { name: "Kütahya", districts: ["Merkez", "Tavşanlı", "Simav", "Gediz", "Emet"] },
  { name: "Malatya", districts: ["Yeşilyurt", "Battalgazi", "Doğanşehir", "Akçadağ", "Darende"] },
  { name: "Manisa", districts: ["Yunusemre", "Şehzadeler", "Akhisar", "Turgutlu", "Salihli", "Soma", "Alaşehir", "Sarıgöl"] },
  { name: "Kahramanmaraş", districts: ["Onikişubat", "Dulkadiroğlu", "Elbistan", "Afşin", "Pazarcık", "Türkoğlu"] },
  { name: "Mardin", districts: ["Artuklu", "Kızıltepe", "Midat", "Nusaybin", "Derik", "Mazıdağı"] },
  { name: "Muğla", districts: ["Bodrum", "Fethiye", "Milas", "Menteşe", "Marmaris", "Sert", "Yatağan", "Ortaca"] },
  { name: "Muş", districts: ["Merkez", "Bulanık", "Malazgirt", "Varto", "Hasköy"] },
  { name: "Nevşehir", districts: ["Merkez", "Ürgüp", "Avanos", "Gülşehir", "Derinkuyu"] },
  { name: "Niğde", districts: ["Merkez", "Bor", "Çiftlik", "Ulukışla", "Altunhisar"] },
  { name: "Ordu", districts: ["Altınordu", "Ünye", "Fatsa", "Gölköy", "Korgan", "Kumru"] },
  { name: "Rize", districts: ["Merkez", "Çayeli", "Ardeşen", "Pazar", "Fındıklı"] },
  { name: "Sakarya", districts: ["Adapazarı", "Serdivan", "Akyazı", "Erenler", "Hendek", "Karasu", "Geyve"] },
  { name: "Samsun", districts: ["İlkadım", "Atakum", "Canik", "Bafra", "Çarşamba", "Vezirköprü", "Terme"] },
  { name: "Siirt", districts: ["Merkez", "Kurtalan", "Baykan", "Eruh", "Şirvan"] },
  { name: "Sinop", districts: ["Merkez", "Boyabat", "Gerze", "Ayancık", "Durağan"] },
  { name: "Sivas", districts: ["Merkez", "Şarkışla", "Yıldızeli", "Suşehri", "Gemerek", "Zara"] },
  { name: "Tekirdağ", districts: ["Çorlu", "Süleymanpaşa", "Çerkezköy", "Kapaklı", "Ergene", "Malkara", "Saray"] },
  { name: "Tokat", districts: ["Merkez", "Erbaa", "Turhal", "Zile", "Niksar", "Reşadiye"] },
  { name: "Trabzon", districts: ["Ortahisar", "Akçaabat", "Araklı", "Of", "Yomra", "Arsin", "Vakfıkebir"] },
  { name: "Tunceli", districts: ["Merkez", "Pertek", "Mazgirt", "Çemişgezek", "Hozat"] },
  { name: "Şanlıurfa", districts: ["Eyyübiye", "Haliliye", "Siverek", "Viranşehir", "Karaköprü", "Akçakale", "Suruç", "Birecik"] },
  { name: "Uşak", districts: ["Merkez", "Banaz", "Eşme", "Sivaslı", "Ulubey"] },
  { name: "Van", districts: ["İpekyolu", "Tuşba", "Edremit", "Erciş", "Özalp", "Çaldıran", "Muradiye"] },
  { name: "Yozgat", districts: ["Merkez", "Sorgun", "Akdağmadeni", "Yerköy", "Boğazlıyan"] },
  { name: "Zonguldak", districts: ["Merkez", "Ereğli", "Çaycuma", "Devrek", "Kozlu", "Kilimli"] },
  { name: "Aksaray", districts: ["Merkez", "Eskil", "Ortaköy", "Gülağaç", "Güzelyurt"] },
  { name: "Bayburt", districts: ["Merkez", "Aydıntepe", "Demirözü"] },
  { name: "Karaman", districts: ["Merkez", "Ermenek", "Sarıveliler", "Ayrancı"] },
  { name: "Kırıkkale", districts: ["Merkez", "Yahşihan", "Keskin", "Delice", "Bahşili"] },
  { name: "Batman", districts: ["Merkez", "Kozluk", "Sason", "Beşiri", "Gercüş"] },
  { name: "Şırnak", districts: ["Cizre", "Silopi", "Merkez", "İdil", "Uludere"] },
  { name: "Bartın", districts: ["Merkez", "Amasra", "Ulus", "Kurucaşile"] },
  { name: "Ardahan", districts: ["Merkez", "Göle", "Çıldır", "Hanak"] },
  { name: "Iğdır", districts: ["Merkez", "Tuzluca", "Aralık", "Karakoyunlu"] },
  { name: "Yalova", districts: ["Merkez", "Çiftlikköy", "Çınarcık", "Altınova", "Armutlu"] },
  { name: "Karabük", districts: ["Merkez", "Safranbolu", "Yenice", "Eskipazar"] },
  { name: "Kilis", districts: ["Merkez", "Musabeyli", "Elbeyli", "Polateli"] },
  { name: "Osmaniye", districts: ["Merkez", "Kadirli", "Düziçi", "Bahçe", "Toprakkale"] },
  { name: "Düzce", districts: ["Merkez", "Akçakoca", "Kaynaşlı", "Çilimli", "Gölyaka"] },
];

export const CAT_BREEDS = [
  "Tekir", "Van Kedisi", "Ankara Kedisi", "British Shorthair", "Scottish Fold", "Siamese", "Persian", "Maine Coon"
];

export const DOG_BREEDS = [
  "Golden Retriever", "German Shepherd", "Poodle", "Bulldog", "Beagle", "Rottweiler", "Siberian Husky", "Chihuahua"
];

export const MOCK_PETS = [
  {
    id: "1",
    name: "Pamuk",
    type: "Kedi",
    breed: "Van Kedisi",
    age: "2 Yaş",
    city: "Van",
    district: "İpekyolu",
    photos: ["https://picsum.photos/seed/cat1/600/800", "https://picsum.photos/seed/cat1b/600/800"],
    description: "Çok uysal ve oyuncu bir kedi. Yeni yuvasını bekliyor.",
    vaccinationStatus: "Tam",
    neuteredStatus: "Kısırlaştırılmış",
    energyLevel: 4,
    toiletTraining: true,
    ownerId: "u1",
    createdAt: new Date().toISOString()
  },
  {
    id: "2",
    name: "Duman",
    type: "Kedi",
    breed: "Tekir",
    age: "6 Aylık",
    city: "İstanbul",
    district: "Beşiktaş",
    photos: ["https://picsum.photos/seed/cat2/600/800"],
    description: "Sokakta bulundu, çok cana yakın.",
    vaccinationStatus: "Eksik",
    neuteredStatus: "Kısırlaştırılmamış",
    energyLevel: 5,
    toiletTraining: true,
    ownerId: "u2",
    createdAt: new Date().toISOString()
  },
  {
    id: "3",
    name: "Max",
    type: "Köpek",
    breed: "Golden Retriever",
    age: "3 Yaş",
    city: "Ankara",
    district: "Çankaya",
    photos: ["https://picsum.photos/seed/dog1/600/800", "https://picsum.photos/seed/dog1b/600/800"],
    description: "Eğitimli, çocuklarla arası çok iyi.",
    vaccinationStatus: "Tam",
    neuteredStatus: "Kısırlaştırılmış",
    energyLevel: 3,
    toiletTraining: true,
    ownerId: "u3",
    createdAt: new Date().toISOString()
  },
  {
    id: "4",
    name: "Zeytin",
    type: "Köpek",
    breed: "Pug",
    age: "1 Yaş",
    city: "İzmir",
    district: "Karşıyaka",
    photos: ["https://picsum.photos/seed/dog2/600/800"],
    description: "Küçük ama enerjisi yüksek.",
    vaccinationStatus: "Tam",
    neuteredStatus: "Kısırlaştırılmış",
    energyLevel: 4,
    toiletTraining: true,
    ownerId: "u4",
    createdAt: new Date().toISOString()
  }
];
